[33mcommit 097675e6202b35e07dc23da4c3082c8f81b7afe1[m
Author: melsov <melsovereign@yahoo.com>
Date:   Tue May 22 13:23:44 2018 -0400

    Terrain shader and distributor

 delete mode 100644 Temp/StagingArea/Mono/EmbedRuntime/MonoPosixHelper.dll
 delete mode 100644 Temp/StagingArea/Mono/EmbedRuntime/mono.dll
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/1.0/DefaultWsdlHelpGenerator.aspx
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/1.0/machine.config
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/Browsers/Compat.browser
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/DefaultWsdlHelpGenerator.aspx
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/machine.config
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/settings.map
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/web.config
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/browscap.ini
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/config
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds.exe
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/Assembly-CSharp-firstpass.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/Assembly-CSharp.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/Mono.Security.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/System.Core.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/System.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AIModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ARModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AccessibilityModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AnimationModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AssetBundleModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AudioModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.BaselibModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ClothModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.CloudWebServicesModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ClusterInputModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ClusterRendererModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.CoreModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.CrashReportingModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.DirectorModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.FacebookModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.GameCenterModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.GridModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.HotReloadModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.IMGUIModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ImageConversionModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.InputModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.JSONSerializeModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.Networking.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ParticleSystemModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ParticlesLegacyModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.PerformanceReportingModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.Physics2DModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.PhysicsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ScreenCaptureModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SharedInternalsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SpatialTracking.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SpatialTrackingModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SpriteMaskModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SpriteShapeModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.StyleSheetsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SubstanceModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TLSModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TerrainModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TerrainPhysicsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TextRenderingModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TilemapModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.Timeline.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TimelineModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UI.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UIElementsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UIModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UNETModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UmbraModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityAnalyticsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityConnectModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestAssetBundleModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestAudioModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestTextureModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestWWWModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.VRModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.VehiclesModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.VideoModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.WebModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.WindModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.XRModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/mscorlib.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Resources/unity default resources
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Resources/unity_builtin_extra
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/app.info
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/boot.config
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/globalgamemanagers
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/globalgamemanagers.assets
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/level0
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/level0.resS
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/sharedassets0.assets
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/sharedassets0.assets.resS
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/sharedassets0.resource
 delete mode 100644 Temp/StagingArea/UnityCrashHandler32.exe
 delete mode 100644 Temp/StagingArea/UnityPlayer.dll
 delete mode 100644 Temp/TarGZ/Breakable Floor Tiles
 delete mode 100644 Temp/UnityVS_obj/Debug/CoreCompileInputs.cache
 delete mode 100644 Temp/UnityVS_obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
 delete mode 100644 Temp/__Backupscenes/0.backup

[33mcommit 64084a3ba6b00c980cf7aa13db0a414390099308[m
Author: melsov <melsovereign@yahoo.com>
Date:   Sun May 20 19:29:48 2018 -0400

    rigidbody player controller

 delete mode 100644 Assets/Scripts/PlayerController.cs
 delete mode 100644 Temp/StagingArea/Mono/EmbedRuntime/MonoPosixHelper.dll
 delete mode 100644 Temp/StagingArea/Mono/EmbedRuntime/mono.dll
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/1.0/DefaultWsdlHelpGenerator.aspx
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/1.0/machine.config
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/Browsers/Compat.browser
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/DefaultWsdlHelpGenerator.aspx
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/machine.config
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/settings.map
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/2.0/web.config
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/browscap.ini
 delete mode 100644 Temp/StagingArea/Mono/etc/mono/config
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds.exe
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/Assembly-CSharp-firstpass.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/Assembly-CSharp.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/Mono.Security.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/System.Core.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/System.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AIModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ARModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AccessibilityModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AnimationModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AssetBundleModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.AudioModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.BaselibModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ClothModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.CloudWebServicesModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ClusterInputModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ClusterRendererModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.CoreModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.CrashReportingModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.DirectorModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.FacebookModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.GameCenterModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.GridModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.HotReloadModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.IMGUIModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ImageConversionModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.InputModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.JSONSerializeModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.Networking.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ParticleSystemModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ParticlesLegacyModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.PerformanceReportingModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.Physics2DModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.PhysicsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.ScreenCaptureModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SharedInternalsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SpatialTracking.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SpatialTrackingModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SpriteMaskModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SpriteShapeModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.StyleSheetsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.SubstanceModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TLSModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TerrainModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TerrainPhysicsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TextRenderingModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TilemapModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.Timeline.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.TimelineModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UI.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UIElementsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UIModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UNETModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UmbraModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityAnalyticsModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityConnectModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestAssetBundleModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestAudioModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestTextureModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.UnityWebRequestWWWModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.VRModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.VehiclesModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.VideoModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.WebModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.WindModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.XRModule.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/UnityEngine.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Managed/mscorlib.dll
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Resources/unity default resources
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/Resources/unity_builtin_extra
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/app.info
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/boot.config
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/globalgamemanagers
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/globalgamemanagers.assets
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/level0
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/level0.resS
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/sharedassets0.assets
 delete mode 100644 Temp/StagingArea/NetworkNoodleBuilds_Data/sharedassets0.assets.resS
 delete mode 100644 Temp/StagingArea/UnityCrashHandler32.exe
 delete mode 100644 Temp/StagingArea/UnityPlayer.dll
 delete mode 100644 Temp/TarGZ/Man in a Suit
